name: Build & Deploy

on:
  push:
    branches:
      - "*"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.*]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install app dependencies
        run: npm i

      - name: Build app
        run: npm build

      - name: Clean up
        run: rm -rf ./node_modules && rm -rf ./dist && rm -rf ./.git;

      - name: Deploying
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deliver
        run: |
          zip -r avalanche-tickets.zip ./;
          scp -oStrictHostKeyChecking=no avalanche-tickets.zip deploy@${{ secrets.SSH_HOST }}:avalanche-tickets.zip;
          scp -oStrictHostKeyChecking=no install.sh deploy@${{ secrets.SSH_HOST }}:install.sh;
          ssh -oStrictHostKeyChecking=no deploy@${{ secrets.SSH_HOST }} <<< $'chmod +x ./install.sh';
          ssh -oStrictHostKeyChecking=no deploy@${{ secrets.SSH_HOST }} <<< $'./install.sh';
